import type { Metadata } from "next";
import "./globals.css";
import { ThemeContextProvider } from "@/context/ThemeContext";
import { LocationContextProvider } from "@/context/LocationContext";

export const metadata: Metadata = {
  title: "Flights",
  description: "Generated by Abraham",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>

      <body className="">
        <ThemeContextProvider>
          <LocationContextProvider>{children}</LocationContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
